version: '3.7'

services:

 db:
  image: mysql:5.7.5
  container_name: db
  volumes:
   - db-data:/var/lib/mysql
  restart: always
  ports:
   - 3306:3306
  environment:
   MYSQL_USER: root
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: test

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  restart: always
  ports:
   - 81:80
  links:
    - db:db

 web:
  image: nginx:latest
  container_name: web
  ports:
   - 80:80
  volumes:
   - ./srcs:/var/www
   - ./site.conf:/etc/nginx/conf.d/default.conf
  depends_on:
    - php

 php:
  build: ./Dockerfiles/php
  container_name: php
  volumes:
   - ./srcs:/var/www
  environment:
   - DOCKER_IP

volumes:
 db-data:
