version: '3.7'

services:

 db:
  image: mysql:5.7.5
  command: --max_allowed_packet=512M --innodb_log_file_size=512M --wait_timeout=31536000
  container_name: db
  volumes:
   - db-data:/var/lib/mysql
  restart: always
  ports:
   - 3306:3306
  environment:
   MYSQL_USER: ${DB_USER}
   MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
   MYSQL_DATABASE: camagru
   TZ: "Europe/Paris"

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  restart: always
  ports:
   - 81:80
  links:
    - db:db

 nginx:
  build:
    context: ./Dockerfiles/nginx
    args:
      - DOCKER_IP=$DOCKER_IP
  container_name: nginx
  restart: always
  ports:
   - 80:80
   - 443:443
  volumes:
   - ./srcs:/var/www
  depends_on:
    - camagru_php

 camagru_php:
  build:
    context: ./Dockerfiles/php
    args:
      - MAIL_USER=$MAIL_USER
      - MAIL_PASSWORD=$MAIL_PASSWORD
  container_name: camagru_php
  restart: always
  volumes:
   - ./srcs:/var/www
  environment:
   - DOCKER_IP
   - DB_USER
   - DB_PASSWORD
   - MAIL_USER
   - MAIL_PASSWORD

volumes:
 db-data:
