version: '3.7'

services:

 db:
  image: mysql:5.7.5
  container_name: db
  command: --max_allowed_packet=32505856
  volumes:
   - db-data:/var/lib/mysql
  restart: always
  ports:
   - 3306:3306
  environment:
   MYSQL_USER: root
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: camagru

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  restart: always
  ports:
   - 81:80
  links:
    - db:db

 nginx:
  build: ./Dockerfiles/nginx
  container_name: nginx
  restart: always
  ports:
   - 80:80
   - 443:443
  volumes:
   - ./srcs:/var/www
  depends_on:
    - php

 php:
  build: ./Dockerfiles/php
  container_name: php
  restart: always
  volumes:
   - ./srcs:/var/www
  environment:
   - DOCKER_IP
   - DB_USER
   - DB_PASSWORD

volumes:
 db-data:
